name: Deploy
on: 
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
